### PR TITLE
Fix media download by updating dependencies

### LINKED ISSUE #12: Fix dependencies
- https://github.com/IonicaBizau/youtube-api/issues/88

WIP: [feature/update-dependencies](https://github.com/danguilherme/spotivy/tree/feature/update-dependencies)

### PR DESCRIPTION
**Pull request by danguilherme**
# PR Details

Upgrade dependencies.

**Description**

- `highland`: `2.11.1` => `2.13.0`
- `left-pad`: `1.1.3` => `1.3.0`
- `spotify-web-api`: `2.3.5` => `5.0.2`
- `youtube-api`: `2.0.2` => `3.0.1`
- `ytdl-core`: `3.1.2` => `4.11.0`

**Related Issue**

Fixes #12

### CODE REVIEW

**Comment by danguilherme** [comment]
Needs testing.

**Comment by Eithoo** [comment]
Spotivy wasn't working after installation - there were problems with **ytdl-core**. I changed version manually to the newest (4.1.4) and now it's working how it's supposed to work. Im kinda new on github and I don't know how to apply that change here, so I'm writing here 😄

**Comment by danguilherme** [comment]
Hey @Eithoo, thanks for the heads up!

I think I can do it now, the other dependency I was waiting on seems to be resolved.
I'll do this as soon as possible. I can't test it extensively, but will do a quick check to make sure everything works as expected.

**Comment by osanchez25** [comment]
Hi , any news on updating this. I tried to make this work but was unable to do it.

**Comment by danguilherme** [comment]
Also fixes #35

**Pull request merged**
